### ISSUE TITLE
Error: Could not create ~/bin/fresh. Do you have permissions?

### ISSUE THREAD

**Issue by Nate-Wilkins** [freshshell/fresh#134]
I'm having a lot of trouble setting up fresh on my local windows box.  When trying to run either install method (```bash -c "`curl -sL get.freshshell.com`"``` or `git clone https://github.com/freshshell/fresh ~/.fresh/source/freshshell/fresh ...`) I get the same error when the script is trying to create `bin/fresh`

I know I'm missing something really obvious but I can't seem to figure it out. Any help is really appreciated!

**Comment by jasoncodes** [comment]
What error message are you receiving? Can you paste the output here?

**Comment by Nate-Wilkins** [comment]
```bash
Error: Could not create /c/Users/UserName/bin/fresh. Do you have permission?
/c/Users/UserName/.freshrc:11: fresh freshshell/fresh bin/fresh --bin
Have a look at the repo: <https://github.com/freshshell/fresh>
```

**Comment by jasoncodes** [comment]
Window’s not normally a platform I use but I just tested on a Windows 10 VM with a default Cygwin x64 install plus the git and curl packages. `bash -c "`curl -sL get.freshshell.com`"` worked fine.

The most likely issue seems like file system permissions. Can you paste the output of both `id -a` and `ls -ld ~ ~/bin ~/bin/fresh`?

**Comment by Nate-Wilkins** [comment]
```bash
$ id -a
uid=500<UserName> gid=544<Administrators> groups=544<Administrators>

$ ls -ld ~ ~/bin ~/bin/fresh
ls: /c/Users/UserNamebin/fresh: No such file or directory
drwxr-xr-x   49 UserName Administ    12288 Dec  7 09:01 /c/Users/UserName
drwxr-xr-x    2 UserName Administ        0 Dec  7 09:01 /c/Users/UserName/bin
```

**Comment by jasoncodes** [comment]
Hmm. That is interesting. I’m not seeing why it should be failing.

Try running `bash -ex ~/.fresh/source/freshshell/fresh/bin/fresh` which will output a log of everything fresh does. Near the end of the output there should be a `_fatal_error` line and a `_fresh_symlink` about 10 or so lines above that. Can you paste this range? I’m expecting to see a `ln -s` line within this range. Does running this line manually trigger output a error message?

**Comment by Nate-Wilkins** [comment]
```bash
++ chmod +x /c/Users/UserName/.fresh/build.new/bin/fresh
++ _fresh_symlink
++ [[ -n bin/fresh ]]
++ [[ -n /c/Users/UserName/bin/fresh ]]
++ SYMLINK_SOURCE=/c/Users/UserName/.fresh/build/bin/fresh
++ SYMLINK_PATH=/c/Users/UserName/bin/fresh
++ '[' -L /c/Users/UserName/bin/fresh ']'
+++ dirname /c/Users/UserName/bin/fresh
++ mkdir -p /c/Users/UserName/bin
++ ln -s /c/Users/UserName/.fresh/build/bin/fresh /c/Users/UserName/bin/fresh
++ SKIP_INFO=1
++ [[ -e /c/Users/UserName/bin/fresh ]]
++ _fatal_error 'Could not create /c/Users/UserName/bin/fresh. Do you have permission?'
++ echo 'Error:' 'Could not create /c/Users/UserName/bin/fresh. Do you have permission?'
Error: Could not create /c/Users/UserName/bin/fresh. Do you have permission?
++ [[ 1 == 1 ]]
+++ _rc_file_line_reference
+++ [[ 1 == 1 ]]
+++ local DISPLAY_RC_FILE=/c/Users/UserName/.freshrc
++++ head -11 /c/Users/UserName/.freshrc
++++ tail -1
+++ local 'RC_CONTENT=fresh freshshell/fresh bin/fresh --bin'
+++ echo '/c/Users/UserName/.freshrc:11: fresh freshshell/fresh bin/fresh --bin'
++ echo '/c/Users/UserName/.freshrc:11: fresh freshshell/fresh bin/fresh --bin'
/c/Users/UserName/.freshrc:11: fresh freshshell/fresh bin/fresh --bin
++ [[ 1 == 1 ]]
++ [[ -n freshshell/fresh ]]
++++ _repo_url freshshell/fresh
++++ local REPO_NAME=freshshell/fresh
++++ echo freshshell/fresh
++++ grep -q :
++++ echo https://github.com/freshshell/fresh
+++ _format_url https://github.com/freshshell/fresh
+++ echo 'https://github.com/freshshell/fresh'
++ echo 'Have a look at the repo: <https://github.com/freshshell/fresh>'
Have a look at the repo: <https://github.com/freshshell/fresh>
++ exit 1
```

Running the failed line by itself does result in an error

```bash
$ ln -s /c/Users/UserName/.fresh/build/bin/fresh /c/Users/UserName/bin/fresh
ln: failed to create symbolic link '/c/Users/UserName/bin/fresh': No such file or directory
```

It's interesting though because it's trying to find `~/.fresh/build/bin/fresh` but all I have locally is `~/.fresh/build.new/bin/fresh`?

**Comment by jasoncodes** [comment]
Moving `build.new` over to `build` (replacing any existing `build`) is intentionally the last step to avoid breaking any existing working setup. Symlinking to a missing source does not fail here and I have never seen this behaviour before.

Can you provide more information as to your environment (OS version, file system, etc.)? It appears you are using Cygwin. Is this correct? The docs say there are a few different modes symlink emulation can run in: https://cygwin.com/cygwin-ug-net/using.html#pathnames-symlinks. Perhaps this needs to be changed/configured?

**Comment by Nate-Wilkins** [comment]
Heh, just realized I should have Cygwin installed but I'm using git bash instead.
```
OS: Windows 10 Pro 64-bit
FS: NTFS
Git: 2.6.3.windows.1
```
Going to blame git bash. Let me install Cygwin and configure my bash correctly.

**Comment by Nate-Wilkins** [comment]
So I installed Cygwin 2.3.1 with a different issue though. This one saying that the downloaded source doesn't have a `bin/fresh` file which is not the case.

```
$ bash -c "`curl -sL get.freshshell.com`"
Cloning into '/home/UserName/.fresh/source/freshshell/fresh'...
remote: Counting objects: 2112, done.
remote: Total 2112 (delta 0), reused 0 (delta 0), pReceivinack-rg obeused jects: 2112
Receiving objects: 100% (2112/2112), 1.29 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (965/965), done.
Checking connectivity... done.
bash: line 53 /home/UserName/.fresh/source/freshshell/fresh/bin/fresh: No such file or directory
```

Some weird stuff is going on wish I was better equipped at figuring this out.

**Comment by jasoncodes** [comment]
Weird indeed. Can you run `~/.fresh/source/freshshell/fresh/bin/fresh` manually after the install script fails? What does `ls -al ~/.fresh/source/freshshell/fresh/bin/fresh` report?

**Comment by Nate-Wilkins** [comment]
It's saying the same thing `No such file or directory` >.<

It's definitely on the file system though. Could this be due to my file system being NTFS?

**Comment by jasoncodes** [comment]
My original sanity test was on Windows 10 with NTFS. How are you verifying the file exists if `ls` doesn’t find it?

**Comment by Nate-Wilkins** [comment]
Windows explorer. Going to look at a few things regarding cygwin and this.

If I create a file in the cygwin terminal (`echo "abc" >> something.txt`) it shows up just fine in the terminal with `ls` but not in windows explorer.
