### ISSUE TITLE
Changing $HOME/bin to $HOME/.local/bin

### ISSUE THREAD

**Issue by umeboshi2** [freshshell/fresh#156]
I've been using fresh for over five years now.  In the last couple of years I decided to stop using ```~/bin``` in favor of ```~/.local/bin```.  During the last couple of years, I had not noticed that ```~/bin``` is still at the head of the $PATH.  I found that this was due to my bashrc sourcing the ```shell.sh``` file generated by fresh.

What I did was add ```FRESH_BIN_PATH=~/.local/bin``` to my freshrc file before calling fresh in that file.  This seems to fix the problem.  My question is "is this the right way to do it, or am I missing something?"

**Comment by jasoncodes** [comment]
Hi there. Glad you find fresh useful. :)

Yes, defining `FRESH_BIN_PATH` at the top of your `freshrc` file is the right way to customise where bin scripts are written.

We can probably make this option easier to discover by mentioning it in the README. We already have #152 for this so I’m going to close this as a duplicate. Cheers.
