### ISSUE TITLE
Is there any method for alternating files? 

### ISSUE THREAD

**Issue by quintrino** [freshshell/fresh#164]
Hi, 

I'm looking at having one line copy a file when I'm on a new computer, and a different file once I've already run fresh, is there anyway to specify in a freshrc file to generate a file from different sources depending on criteria?

**Comment by jasoncodes** [comment]
Hi there,

I’m interested in your particular use case here as to why you’d want the first run to do something different.

In any case, you could use a shell conditional to output different content based on the presence of an output file:

```sh
if [ -f ~/.some-file ]; then
  fresh some-file-first --file=~/.some-file
else
  fresh some-file --file=~/.some-file
fi
```

**Comment by quintrino** [comment]
Hmm, 

I tested it by adding
```
if [ -z "$var" ]; then
  echo "\$var is empty"
else
  echo "\$var is NOT empty"
fi
```

And I get the error

```
$var is empty
filter failed at /Users/nick.wolf/bin/fresh line 218.
	main::apply_filter('#!/bin/sh\x{a}\x{a}export PATH="/usr/local/sbin:$PATH"\x{a}', 'erb') called at /Users/nick.wolf/bin/fresh line 723
	main::file_contents('HASH(0x7fafc5b0cd40)', '/Users/nick.wolf/.dotfiles/', '/Users/nick.wolf/.dotfiles/shell/path') called at /Users/nick.wolf/bin/fresh line 794
	main::fresh_install() called at /Users/nick.wolf/bin/fresh line 1250
	main::main() called at /Users/nick.wolf/bin/fresh line 1280
```

Which appears to be filter related, but then if I remove all the filters on my freshrc file I get this instead. 

```$var is empty
callback failed at /Users/nick.wolf/bin/fresh line 262.
	main::run_callback('after_build', '/Users/nick.wolf/.config/fresh/build') called at /Users/nick.wolf/bin/fresh line 866
	main::fresh_install() called at /Users/nick.wolf/bin/fresh line 1250
	main::main() called at /Users/nick.wolf/bin/fresh line 1280
```

If I do set var then I get 
```
var='string' fresh
$var is NOT empty
Your dot files are now fresh.
```

Could there be something interfering with having and then not setting an environment variable? 

My use case is 
if [ -z "$USE_STATIC_ASDF" ]; then
  fresh dynamic_asdf etc
else
  fresh static_asdf etc
fi

(dynamic asdf is setting the my language global versions to the latest available)

**Comment by quintrino** [comment]
I've found a temporary solution in that I can set FRESH_ASDF_MODE=dynamic in my environment variables and then just run FRESH_ASDF_MODE=static when I need to.

**Comment by jasoncodes** [comment]
Fresh evaluates the `freshrc` file in a mode which errors on undefined variables. This is intentional behaviour to prevent typos.

You can use ` [ -z "${FRESH_ASDF_MODE:-}" ]` if you wish to skip this safety for a particular variable you may not have defined.
