### ISSUE TITLE
Fresh ZSH completion does not work

### ISSUE THREAD

**Issue by bjeanes** [freshshell/fresh#166]
```
~/.dotfiles ♪  fresh [PRESS TAB]...Error: Unknown command: commands

_values:compvalues:11: not enough arguments
Error: Unknown command: commands
_values:compvalues:11: not enough arguments
Error: Unknown command: commands
_values:compvalues:11: not enough arguments
Error: Unknown command: commands
_values:compvalues:11: not enough arguments
Error: Unknown command: commands
_values:compvalues:11: not enough arguments
```

The implementation relies on the presence of a `fresh commands` sub-command in the CLI, which does not appeart to exist (any more?): https://github.com/freshshell/fresh/blob/c270fab4886381ee97a022c5c5650440c3ee0033/contrib/completion/fresh-completion.zsh#L18

**Comment by jasoncodes** [comment]
Thanks for reporting this issue. Looks like we missed `fresh commands` when we re-wrote fresh in Perl.

Fixed by a586b69...1cee6dd.
