### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by delucca** [freshshell/fresh#171]
Hi!

Amazing job you've done here :)

I would like to know if there is a way to use environment variables upon fresh dotfiles installation?

I have an old dotfile script that uses `envsubst` to create custom dotfiles based on environment variables.

**Comment by jasoncodes** [comment]
Hi there.

Existing environment variables will be available in `freshrc` if you want to do scripting (it’s a shell script). You can also use `--filter=envsubst` on a fresh line to perform substitution on your config files. Note that `--filter` can also refresh a function defined within your `freshrc`.

The question is how are those environment variables being set. If you are using things like `$HOME`, `$USER`, `$HOSTNAME`, etc which are typically always set, then you should be good to go. If you are using custom environment variables then you could `export` or `source` them in your `freshrc` file and will be made available to filters.

**Comment by delucca** [comment]
> Hi there.
> 
> Existing environment variables will be available in `freshrc` if you want to do scripting (it’s a shell script). You can also use `--filter=envsubst` on a fresh line to perform substitution on your config files. Note that `--filter` can also refresh a function defined within your `freshrc`.
> 
> The question is how are those environment variables being set. If you are using things like `$HOME`, `$USER`, `$HOSTNAME`, etc which are typically always set, then you should be good to go. If you are using custom environment variables then you could `export` or `source` them in your `freshrc` file and will be made available to filters.

Great!

Thanks for your quick response.
