### ISSUE TITLE
How to allow write in dotfile

### ISSUE THREAD

**Issue by delucca** [freshshell/fresh#172]
Hi everyone!

I'm loving the lib, using it a lot :)

I'm trying to backup my dconf config (located at `~/.config/dconf`). To do so, I just need to create a symlink between the dotfile folder and the original one.

I was able to do that with fresh, but it mounts the file as read-only, and that breaks my OS (since dconf is pretty sensitive, we need to allow write in it).

There is any any to link the dotfile directly? Without building it to a different folder to protect against writes?

**Comment by twe4ked** [comment]
We don't have a way to support writable files at the moment, there are some tricky considerations to do with concatenating multiple files and how to handle updating the file if it comes from a remote source.

For now you can add a manual `ln -s` in the `fresh_after_build` hook, [here's an example](https://github.com/twe4ked/dotfiles/blob/f58c3c94c64e23eb5ad7aada8d29260d46d7d11c/freshrc#L150-L152)

**Comment by twe4ked** [comment]
Here's the tracking issue: https://github.com/freshshell/fresh/issues/66

Feel free to add more context there!

There is also another suggestion from @jsoncodes there.
