### ISSUE TITLE
What is fresh? Is it a plugin manager for Bash?

### ISSUE THREAD

**Issue by psprint** [freshshell/fresh#175]
Hi,
looking at Readme it's hard to get a notion of what `fresh` *is*. Could someone shed some light on it?

**Comment by twe4ked** [comment]
fresh is “build tool”/“preprocessor” for dotfiles/config files. It could be described as similar to Webpack.

You use a `freshrc` file to define what files you want to build and where you want them to be symlinked to. You can either use local files and/or remote files, for instance files hosted on GitHub. You can also split up files into logical components and combine them together.
