### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by 0xdevalias** [freshshell/fresh#179]
I recently stumbled across this project via https://github.com/unixorn/awesome-zsh-plugins#frameworks, and I was wondering if this project is still actively developed/maintained? The last commit (at time of writing) seems to be in [August 2021](https://github.com/freshshell/fresh/commit/2e4dc6e70bcc95bde4d37bbce3e34dc19bfebca2):

- https://github.com/freshshell/fresh/commits/master

While I haven't exhaustively searched for alternatives yet, this is one I stumbled across that seems to potentially solve a similar need/problemspace (in case this repo isn't maintained, as it currently seems):

- https://github.com/b4b4r07/afx
  - > AFX is a package manager for command-line tools and shell plugins. afx can allow us to manage almost all things available on GitHub, Gist and so on. Before, we needed to trawl web pages to download each package one by one. It's very annoying every time we set up new machine and also it's difficult to get how many commands/plugins we installed. So afx's motivation is coming from that and to manage them with YAML files (as a code).

**Comment by jasoncodes** [comment]
The core developers (myself included) active use fresh and consider it to be stable and without any significant bugs. We have a wish list for future features (most of them are logged as Issues) however the current functionality meets our needs as it stands now. This is why there are no recent commits.

AFX appears like it is aiming to be a general tool for installing things where as fresh is designed specifically for dotfiles. I expect you could use AFX for dotfiles too but it’ll require more configuration.
